openapi: 3.0.1
info:
  title: bank-api
  description: 'bank-api'
  version: 1.0.0
servers:
- url: https://bank-code-api.herokuapp.com/
- url: http://localhost:3000
paths:
    /boleto/{value}:
      get:
        parameters:
        -   in: path
            name: value
            required: true
            schema:
                type: string
        responses:
            200:
                description: ""
                content: {}
